export default {
  MIN_EXCHANGE_AMOUNT: 0.10,
  UPDATE_RATE_FREQUENCY: 10,
  FREE_EXCHANGE_LIMIT: 5000,
  EXCHANGE_FEE_PERCENTAGE: 0.005,
  API_HOST: 'https://data.fixer.io',
  GET_LATEST_RATE: '/api/latest',
  APP_ID: process.env.REACT_APP_API_KEY,
  EXCHANGE_BASE_CODE: 0,
  MAX_AMOUNT_LENGTH: 18
}